### ISSUE TITLE
jar files for web and scheduler are not downloadable

### ISSUE THREAD

**Issue by carolyn0429** [Damianofds/taskmanager#2]
I am not able to download web and scheduler jar files from "Configuration Database" option 1...

**Comment by Damianofds** [comment]
Ciao Carolyn,
The candidates are asked to build the project by their own with maven and producing executable jars or docker images. You can find building instructions [here on the readme](https://github.com/Damianofds/taskmanager#build). Have a look to the project poms or feel free to ask for any specific question if something is not clear to you.

With that said, I reviewed the document of the engineering challenge you have and this was not explicitly mentioned, I now added it. Sorry for causing you waste of time for this.

We look forward to hearing back from you!
