### ISSUE TITLE
Some issues with 'Services'

### ISSUE THREAD

**Issue by Vetochka404** [Damianofds/taskmanager#6]
Dear team,

I met some problem during preparing test task.
First of all, I did not find any information about DB. Which tables, columns there should be? 
Next, the links from 'Download the web and the scheduler jar files' do not work. Could you check them? 
I've got an error with 'writeAndReadOnDB' class and it interrupts my work. 

I don't have much experience with developing, that's why it's quite complicated to success in this task without appropriate skills.

Could you fix the issues above?

Thanks!

**Comment by Damianofds** [comment]
Hi @Vetochka404 the jars aren't online anymore and you should build them following https://github.com/Damianofds/taskmanager/blob/master/README.md#build . Sorry, the readme was outdated on that part, I just updated it.

If you import in your IDE the codebase you can run from there all the components in testing mode, spring-boot + JPA will create on the fly an H2 file database before each test run. To have both scheduler and web components running together you have to configure as datasource of the application a db server (I suggest PostgreSQL).
The only table in the DB is created by JPA from this Entity Class https://github.com/Damianofds/taskmanager/blob/master/persistance/src/main/java/it/fds/taskmanager/model/Task.java

(yes the challenge requires some java dev skills... take your time and feel free to ask precise technical questions here, it's kind of fun at the end ;)
