### ISSUE TITLE
Error while running 'java -jar endpoints-0.1-SNAPSHOT.jar'

### ISSUE THREAD

**Issue by kuulrahool** [Damianofds/taskmanager#8]
Hi,

I am following instructions in README file to setup environment for buggy-taskmanager.
I am able to build the project, however 'java -jar endpoints-0.1-SNAPSHOT.jar' is giving errors.

below is the error.
org.postgresql.util.PSQLException: FATAL: database "s_ink" does not exist

Logs are attached for reference.
[endpoints-0.1-SNAPSHOT -  errors.txt](https://github.com/Damianofds/taskmanager/files/2385602/endpoints-0.1-SNAPSHOT.-.errors.txt)

**Comment by Damianofds** [comment]
Hi @kuulrahool, 
sorry for the delay in replying on my side.

It seems that the database **s_ink** doesn't exist. The Readme.md suggest to call it taskmanager and this is probably wrong anyway:

- Did you try to update the application.properties regarding the db connection parameters of both scheduler and web as reported on the Readme.md?
- Did you try to rename the db **s_ink** instead of  **taskmanager**?

Let me know if it solve the issue!

Regards,
Damiano

**Comment by kuulrahool** [comment]
Hi Damiano,
Sorry for the late reply.
Thank you, it worked after renaming the Database.

However, while working with the buggy application I see below tests are failing.

 @Test
    public void taskServiceFunctionTest() {
        TaskDTO t = new TaskDTO();
        t.setTitle("Test task3");
        t.setStatus(TaskState.NEW.toString().toUpperCase());
        TaskDTO t1 = taskService.saveTask(t);
        assertTrue(taskService.resolveTask(t1.getUuid()));
        assertEquals(t1.getStatus(),"RESOLVED");
       
       
    }
    
    @Test
    public void Bug() {
        TaskDTO t0 = new TaskDTO();
        TaskDTO t1 = new TaskDTO();
        TaskDTO t2 = new TaskDTO();
        TaskDTO t3 = new TaskDTO();
        t0.setTitle("Test task0");
        t1.setTitle("Test task1");
        t2.setTitle("Test task2");
        t3.setTitle("Test task3");
        t0.setStatus(TaskState.NEW.toString().toUpperCase());
        t1.setStatus(TaskState.NEW.toString().toUpperCase());
        t2.setStatus(TaskState.RESOLVED.toString().toUpperCase());
        t3.setStatus(TaskState.NEW.toString().toUpperCase());
        taskService.saveTask(t0);
        taskService.saveTask(t1);
        taskService.saveTask(t2);
        taskService.saveTask(t3);
        List<TaskDTO> list = taskService.showList();
        assertEquals(4, list.size());
        t0.setStatus(TaskState.POSTPONED.toString().toUpperCase());
        t1.setStatus(TaskState.POSTPONED.toString().toUpperCase());
        t2.setStatus(TaskState.POSTPONED.toString().toUpperCase());
        t3.setStatus(TaskState.POSTPONED.toString().toUpperCase());
        taskService.showList();
        assertEquals(0, list.size());
      
       
    }

I am not able to change the state of the task using taskService.postponeTask() and taskService.resolveTask().

Also showlist() function is returning count of postponed tasks also.

Please advise if my understanding is correct.

**Comment by Damianofds** [comment]
Hi Priyadarshi,

Did you attach any log? I have only gmail app access right now, I may have
missed it.

Anyway:

*I am not able to change the state of the task using
taskService.postponeTask() and taskService.resolveTask().*

Why? do you get any error?

*Also showlist() function is returning count of postponed tasks also.*

As far as I remember yes, but you have access to the code, why asking? :)


Regards,

Damiano

**Comment by kuulrahool** [comment]
Thank you so much Damiano.

Regards
Rahul
