### ISSUE TITLE
Application Bug

### ISSUE THREAD

**Issue by pandaamitabh** [Damianofds/taskmanager#9]
Hi Damiano,

The application has no explicit mapping for /error. Below is the screen-shot for the same.

![image](https://user-images.githubusercontent.com/43248324/45669208-ed643780-bb3c-11e8-90c8-1352082dbb46.png)

Submit a new task from the UI is not working.

![image](https://user-images.githubusercontent.com/43248324/45669275-2d2b1f00-bb3d-11e8-9804-a497bee7557c.png)

Regards,
Amitabh

**Comment by Damianofds** [comment]
Hi @pandaamitabh,
Regarding the first screenshot you are trying triggering manually the endpoint `/task/create`.
That endpoint doesn't exist: as you can see [here](https://github.com/Damianofds/taskmanager/blob/master/endpoints/src/main/java/it/fds/taskmanager/rest/endpoints/TasksController.java#L82) the @RequestMapping annotation is disabled.

Regarding the second screenshot it's not clear to me what are you trying to do: **you can't create new tasks from the UI**, you can only modify, resolve or postpone existing tasks. The tasks are periodically generated by another application called "scheduler".

**Comment by pandaamitabh** [comment]
Thanks Damiano for the information.
